sudo: required
language: generic
services: docker

script:
- docker pull yannishuber/embeddedjfx8:latest
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/tmp,type=bind yannishuber/embeddedjfx8:latest gradle embeddedJar

deploy:
  provider: releases
  api_key:
    secure: LP8a4Y/Pd8kIFGgW3rr/UNHDtk4CEBIKRI7FSsEpL1cOlvDW5F9rxXZdiP0OubzgEbvEQclH3J0ROB9T6OdZIBAguWZ4levXZ/ue1ZNwfCe5BObVkiUyCmN0ySHF+d4WDbAbkCXY/cDSdqNVjI4d2uG58uJtVwFbyNypdvxMLvrj6qbUZJ0ErMIk0ANLhZrmkdbvUHaMN0x4j2JF82tbQkg2IQSyZYmnZIndsIcbYCRbbRkB+mNHLhdJfgFkCatHD7tYy54DLRVT9YgPvJ/kbPoKOlbLDtgvgpaoF3SUzH2Cz8JDnJ7SPIOO+7XMpXYigfqstaZFrOHSL65IXmAh5/eO+5eX9mxL2SYBWQ25wXqxNw2kuO3OP96dnchbHU0UDNgFrDKdIosPncZfxuHMNK5c9t1vLAuYgjgdX8Qoc9tSG1HoUchmMi3gV9yV/FyZip1pzwgyBURBcVvvWdqFZ6/aTi76T9A4fzN6oouUKTtnX3wdQwCuY2ojNGZuGGegXhbMLmgWg7ndD5mbu2zbZSrKI4EXO9vBX5wxDgumvQUMDQLmOYdJdpV8u1r0avUNU8VxNYXXm35TMix6t9uBjErLwRLUYRnAuuLpjpyzzVrrO20XPhRVQO/FgVtFTrsz/+iSsdu/WFJNnkqfvzIbToLm3eZHfiUXQJkAkINqR5I=
  file: build/javafxports/embedded/libs/*.jar
  skip_cleanup: true
  on:
    tags: true
    repo: solesol-ch/rpi-data-viewer
