/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.solesol.pidataviewer.api;

import ch.solesol.pidataviewer.api.objects.DataModel;
import ch.solesol.pidataviewer.api.objects.solaredge.SolaredgeModel;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class SolaredgeAPITest {

    DataModel dm;

    @Before
    public void initializeObjects() {
        dm = new SolaredgeModel();
    }

    @Test public void testCurrentPowerFlow() {
        System.out.printf("Current production: %f\n", dm.getCurrentProduction());
        if(dm.currentlyProducing()) assertTrue(dm.getCurrentProduction() > 0);
        else assertEquals(dm.getCurrentProduction(), 0, 0.001);

        System.out.printf("Current usage: %f\n", dm.getCurrentUsage());
        System.out.printf("Current feed in/out: %f\n", dm.getCurrentFeedInOut());
        System.out.printf("isProducing : %b\n", dm.currentlyProducing());
        System.out.printf("isConsuming : %b\n", dm.currentlyConsuming());
    }
}
