/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.solesol.pidataviewer;

import javafx.application.Application;
import javafx.beans.property.SimpleStringProperty;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import java.util.concurrent.atomic.AtomicInteger;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        Label l = new Label();
        SimpleStringProperty s = new SimpleStringProperty("Clicks: 0");
        l.textProperty().bind(s);
        Button b = new Button("Touch me");
        AtomicInteger clicks = new AtomicInteger();
        b.setOnAction((e) -> {
            s.setValue(String.format("Clicks : %d", clicks.incrementAndGet()));
        });
        Scene scene = new Scene(new StackPane(b, l), 320, 240);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

}
