/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.solesol.pidataviewer;

import ch.solesol.pidataviewer.api.objects.DataModel;
import ch.solesol.pidataviewer.api.objects.solaredge.SolaredgeModel;
import javafx.application.Application;
import javafx.stage.Stage;


public class App extends Application {

    @Override
    public void start(Stage stage) {

        /*Label l = new Label();
        SimpleStringProperty s = new SimpleStringProperty("Clicks: 0");
        l.textProperty().bind(s);
        Button b = new Button("Touch me");
        AtomicInteger clicks = new AtomicInteger();
        b.setOnAction((e) -> {
            s.setValue(String.format("Clicks : %d", clicks.incrementAndGet()));
        });
        Scene scene = new Scene(new VBox(b, l), 320, 240);
        stage.setScene(scene);
        stage.show();*/

        DataModel dm = new SolaredgeModel();
        System.out.println("DONE");
    }

    public static void main(String[] args) {
        launch();
    }

}
