/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.solesol.pidataviewer;

import ch.solesol.pidataviewer.api.objects.DataModel;
import ch.solesol.pidataviewer.api.objects.solaredge.SolaredgeModel;
import javafx.application.Application;
import javafx.beans.property.SimpleStringProperty;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.io.IOException;
import java.util.concurrent.atomic.AtomicInteger;


public class App extends Application {

    @Override
    public void start(Stage stage) {


        FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/Dashboard.fxml"));
        GridPane root = null;
        try {
            root = loader.load();
        } catch (IOException e) {
            e.printStackTrace();
        }
        DashboardController controller = loader.getController();


        Scene scene = new Scene(root, 320, 240);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

}
